<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   EOI
 * @package    EOI_WonderFaye
 * @copyright  Copyright (c) 2012 EOI (http://www.eoi.com)
 */
 $pelepay_resp_msg      = Mage::getSingleton('core/session')->getPelepayResMsg();
 $pelepay_resp_msg_code = Mage::getSingleton('core/session')->getPelepayResMsgCode();
?>
<html>
<meta http-equiv="refresh" content="0; URL=<?php echo $this->getContinueShoppingUrl()?>">
<body>
<div class="page-head">
    <h3><?php echo Mage::helper('pelepay')->__('PelePay Transaction Error occurred') ?></h3>
	<BR />
	<p><?php echo Mage::helper('pelepay')->__('The Error Response Code From PelePay is :')?>&nbsp;&nbsp;<span style="color:red"><b><?php echo Mage::helper('pelepay')->__($pelepay_resp_msg_code) ?></b></span></p>
	<BR />
	<p><?php echo Mage::helper('pelepay')->__('The Error Response From PelePay is :')?>&nbsp;&nbsp;<span style="color:red"><b><?php echo Mage::helper('pelepay')->__($pelepay_resp_msg) ?></b></span></p>
</div>
<p><?php echo Mage::helper('pelepay')->__('Please <a href="%s">continue shopping</a>.', $this->getContinueShoppingUrl()) ?></p>
</body>
</html>