<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   EOI
 * @package    EOI_WonderFaye
 * @copyright  Copyright (c) 2012 EOI (http://www.eoi.com)
 */
<?php
	echo $this->getMethod()->getTitle() . '<br/>';
	if ($this->getInfo()->getLastTransId() == '') {
		echo Mage::helper('pelepay')->__('Payment has not been processed yet.') . '<br/>';
	} else {
	    echo Mage::helper('pelepay')->__('Credit Card Type: %s', $this->htmlEscape($this->getInfo()->getCcType())) . '<br/>';
		echo Mage::helper('pelepay')->__('Pele-Pay Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
		echo Mage::helper('pelepay')->__('AVS status: %s', $this->htmlEscape($this->getInfo()->getCcAvsStatus())) . '<br/>';
		if ($additional_data = $this->getInfo()->getAdditionalData()) {
		  echo Mage::helper('pelepay')->__('Fraud status: %s', $this->htmlEscape($additional_data)) . '<br/>';
		}
	}
?>